export const ROUTES = {
  LOGIN:          '/login',
  DASHBOARD:      '/dashboard',
  BOOK_PARCEL:    '/dashboard/book-parcel',
  INVOICES:       '/dashboard/invoices',
  LOAD_SHEET:     '/dashboard/load-sheet',
  COMPLAINTS:     '/dashboard/complaints',
  ADMIN:          '/dashboard/admin',
  ADMIN_USERS:    '/dashboard/admin/users',
  ADMIN_SETTINGS: '/dashboard/admin/settings',
  SHIPMENTS:      '/dashboard/shipments',
  SHIPMENT_CREATE: '/dashboard/book-parcel',
  SHIPMENT_DETAIL: (id: string) => `/dashboard/shipments/${id}`,
  SETTINGS:       '/dashboard/admin/settings',
} as const;
